sentry: remove the default secret-key
sentry-kubernetes/charts pull request #123
Opened 2020-07-21 09:20 UTC by yoan-adfinis

Providing a default secret key is probably a security issue if it doesn't get changed.

2020-07-21 09:56 UTC, Mokto commented
Ah, thanks!

I'm not sure about this one to be honest. I like the simplicity about installing it without anything required (at least for testing purposes).

Maybe just adding a note to the readme would be enough?

@DandyDeveloper @J0sh0nat0r what do you think?

2020-07-21 12:31 UTC, yoan-adfinis commented
When _testing_ purposes end up on the internet people are crying.

2020-07-22 07:39 UTC, DandyDeveloper commented
@yoan-adfinis @Mokto Both implementations are wrong IMO, although always up for debate.

We should leave nil and generate a random pass, then in the output of Helm, pass this to the user: 

`{{ default (randAlphaNum 15) .Values.somePassword | b64enc | quote }}`

This does mean it's regenerated on upgrade, so we need to make sure it's documented that this password needs to be passed next time.

2020-07-23 06:36 UTC, Mokto requested changes

2020-07-23 06:36 UTC, Mokto commented on sentry/values.yaml
> +  secretKey: ~  # This will generate one for you (it's must be given upon updates)
I would assume we need to comment this line instead ?

2020-07-23 06:36 UTC, Mokto commented on sentry/README.md
> +`sentry.secretKey` | **Required** secret key for the session cookie ([documentation](https://develop.sentry.dev/config/#general)) | `nil`
I think you can remove *required*.

Also, could you add a specific note to the readme ?
Similar to https://github.com/sentry-kubernetes/charts#postgressql

2020-07-23 06:37 UTC, Mokto commented
Agreed @DandyDeveloper.

And thanks for your work on this @yoan-adfinis

2020-07-24 08:04 UTC, Mokto commented
Thanks!

2020-07-24 08:04 UTC, merged