feat: add externalrabbitmq support
sentry-kubernetes/charts pull request #1558
Opened 2024-10-17 03:00 UTC by 2005wind

hi, i want to  add  externalrabbitmq support, pls review . tks .

2024-10-17 03:49 UTC, nadecancode commented
I believe externalRabbitmq is already supported, you just have to set rabbitmq.enabled to false AND specify a host.

2024-10-17 14:40 UTC, nadecancode requested changes

2024-10-17 14:40 UTC, nadecancode commented on charts/sentry/templates/sentry/_helper-sentry.tpl
> -  {{- if or (.Values.rabbitmq.enabled) (.Values.rabbitmq.host) }}
This is not backwards compatible, my deployment relies on this to get the external rabbit running

2024-10-22 07:16 UTC, Mokto commented
External rabbitmq is already supported indeed.

Thanks for the PR anyways.

2024-10-22 07:16 UTC, closed without merging