configurable service account
sentry-kubernetes/charts pull request #380
Opened 2021-05-12 08:52 UTC by kimxogus

For EKS IRSA, this is necessary

2021-05-24 03:08 UTC, kmmanto commented
Would like to see this merged.

2021-05-25 06:47 UTC, Mokto requested changes

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-relay.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-sentry-cron.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-sentry-ingest-consumer.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-sentry-post-process-forwarder.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-sentry-web.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-sentry-worker.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-snuba-api.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-snuba-consumer.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-snuba-outcomes-consumer.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-snuba-replacer.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-snuba-sessions-consumer.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-snuba-transactions-consumer.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/templates/deployment-symbolicator.yaml
> +      serviceAccountName: {{ include "sentry.serviceAccountName" . }}
make it optional

2021-05-25 06:47 UTC, Mokto commented on sentry/values.yaml
>      minReplicas: 2
Please remove all your changes done by your linter.

2021-05-25 06:47 UTC, Mokto commented on sentry/values.yaml
> +  create: true
Should be false per default.

2021-05-25 06:56 UTC, Mokto requested changes

2021-05-25 06:56 UTC, Mokto commented on sentry/values.yaml
> +  create: true
Also I believe you're not really creating the proper service account?

2021-08-25 10:28 UTC, z0rc commented
@kimxogus please check linked PR, support of serviceAccounts was added recently. If you're still interested in existingSecret for externalPostgresql, please update the PR or factor those changes into new PR.

2024-04-12 05:28 UTC, Mokto commented
I'm closing this PR as it's really old. Feel free to reopen it if needed.

2024-04-12 05:28 UTC, closed without merging